# standalone resource-claim with parameters without andy Pod consuming it
apiVersion: gpu.resource.intel.com/v1alpha2
kind: GpuClaimParameters
metadata:
  name: gpu-params0
  namespace: default
spec:
  count: 1
  type: "gpu"
  memory: 256
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaim
metadata:
  name: gpu-claim0
spec:
  allocationMode: Immediate
  resourceClassName: intel-gpu
  parametersRef:
    apiGroup: gpu.resource.intel.com/v1alpha2
    kind: GpuClaimParameters
    name: gpu-params0
