kind: ConfigMap
apiVersion: v1
metadata:
  name: defaults
  namespace: intel-gaudi-resource-driver
data:
# It is possible to override driver hardcoded defaults:
# - resourceClaimParameters:
#     if resource claim did not include any parameters, these will be used
  resourceClaimParameters.config: |
    count=1
