# Configure Intel GPU resource driver alert-webhook for Prometheus Alertmanager.
#
# prometheus-operator validates and generates another secret of this
# (together with possible CRs) and gives it to alertmanager as configMap:
# $ kubectl -n monitoring create secret generic --dry-run=client -o yaml \
#   alertmanager-main --from-file=alertmanager.yaml | kubectl apply -f -
#
# Config format: https://prometheus.io/docs/alerting/latest/configuration/
---
global:
  resolve_timeout: 5m
inhibit_rules:
- equal:
  - namespace
  - alertname
  source_match:
    severity: "critical"
  target_match_re:
    severity: "warning|info"
- equal:
  - namespace
  - alertname
  source_match:
    severity: "warning"
  target_match:
    severity: "info"
receivers:
- name: "Default"
- name: "Watchdog"
- name: "Critical"
- name: "GPU_Health"
  webhook_configs:
  - url: "http://alert-webhook.intel-gpu-resource-driver.svc.cluster.local/alertmanager/api/v1/alerts"
    send_resolved: true
    max_alerts: 0
route:
  group_by:
  - namespace
  receiver: "Default"
  # initial wait for alerts within group
  group_wait: 30s
  # how long to wait for more alerts, before routing alert
  group_interval: 5m
  # multiple of "group_interval", default = 4h
  repeat_interval: 12h
  routes:
  - receiver: "GPU_Health"
    # initial wait for receiving grouped alerts
    group_wait: 2s
    # wait for new alerts after sending initial notification,
    # should be multiple of group_wait, preferably at least 4x:
    # https://github.com/prometheus/alertmanager/issues/2447
    group_interval: 10s
    # TODO: at least several minutes in production
    # (it's this small just to get Alertmanager resend events in testing)
    # notification resend interval, should be multiple of group_interval
    repeat_interval: 20s
    group_by:
    - alertname
    - namespace
    - service
    match_re:
      service: "intel-xpumanager|collectd-gpu-plugin"
    continue: true
  - receiver: "Watchdog"
    match:
      alertname: "Watchdog"
  - receiver: "Critical"
    match:
      severity: "critical"
