# Service for tainting GPUs in node CRs, based on Alertmanager notifications
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intel-gpu-dra-alert-webhook
  namespace: intel-gpu-resource-driver
  labels:
    app: intel-gpu-dra-alert-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intel-gpu-dra-alert-webhook
  template:
    metadata:
      labels:
        app: intel-gpu-dra-alert-webhook
    spec:
      serviceAccount: intel-gpu-alert-webhook-service-account
      serviceAccountName: intel-gpu-alert-webhook-service-account
      # do not hesitate to kill
      terminationGracePeriodSeconds: 5
      containers:
      - name: alert-webhook
        image: intel/intel-gpu-resource-driver:v0.3.0
        imagePullPolicy: Always
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ "ALL" ]
          readOnlyRootFilesystem: true
          runAsUser: 65535
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # Options:
        # * "--address": on which address to listen for Alertmanager notifications
        # * "groups" / "values": only alerts with specified (comma separated)
        #   group labels and their values are accepted
        # * "--alerts": used to restrict CR GPU tainting to be done only
        #   for specified (comma separated) alerts
        # * "--http-only": used to temporarily disable CR updates
        #   (while still accepting Alertmanager notifications)
        command: [
          "/alert-webhook",
          "--address", ":7777",
          "--groups", "namespace,service",
          "--values", "monitoring,collectd-gpu-plugin",
          "-v", "3",
        ]
        # HTTP server port
        ports:
        - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  # service name
  name: alert-webhook
  namespace: intel-gpu-resource-driver
spec:
  selector:
    # pod name
    app: intel-gpu-dra-alert-webhook
  ports:
  - name: http
    port: 80
    targetPort: 7777
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: intel-gpu-alert-webhook-service-account
  namespace: intel-gpu-resource-driver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: intel-gpu-alert-webhook-role-binding
  namespace: intel-gpu-resource-driver
subjects:
- kind: ServiceAccount
  name: intel-gpu-alert-webhook-service-account
  namespace: intel-gpu-resource-driver
roleRef:
  kind: ClusterRole
  name: intel-gpu-alert-webhook-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: intel-gpu-alert-webhook-role
  namespace: intel-gpu-resource-driver
rules:
- apiGroups: ["gpu.resource.intel.com"]
  resources: ["gpuallocationstates"]
  # updates existing GAS CRD, so no need for "create" or "delete"
  verbs: ["get", "list", "watch", "update", "patch"]
