# Job for clearing taints from node given on alert-webhook command line.
# CRD access relies on webhook "intel-gpu-alert-webhook-service-account"
# being already present.
---
apiVersion: batch/v1
kind: Job
metadata:
  name: intel-gpu-dra-node-taint-cleaner
  namespace: intel-gpu-resource-driver
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccount: intel-gpu-alert-webhook-service-account
      serviceAccountName: intel-gpu-alert-webhook-service-account
      containers:
      - name: node-taint-cleaner
        # Change reason to non-empty string to taint all node GPUs
        command: ["/alert-webhook", "-v", "5", "--node", "cml-s-2", "--reason", ""]
        image: intel/intel-gpu-resource-driver:v0.3.0
        imagePullPolicy: Always
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ "ALL" ]
          readOnlyRootFilesystem: true
          runAsUser: 65535
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      # do not hesitate to kill
      terminationGracePeriodSeconds: 5
  # remove 2 min after completion
  ttlSecondsAfterFinished: 120
  backoffLimit: 0
