apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: intel-xpumanager
    app.kubernetes.io/part-of: intel-xpumanager
    prometheus: k8s
    role: alert-rules
  name: xpum-alert-rules
  namespace: monitoring
spec:
  groups:
  # TODOs:
  # - alert only on error count changes, not about high but stable error counts?
  # - use suitable interval [1] in "for" fields, and update summary/description accordingly
  #
  # [1] the time taken to generate an alarm varies between:
  # - minimum time = [time set in the 'FOR' clause]
  # - maximum time = [scrape_interval + evaluation_interval + 'FOR' clause time]
  # where (scrape and) rule evalution intervals are *1 min* by default:
  #   https://prometheus.io/docs/prometheus/latest/configuration/configuration/
  - name: xpum-alerts
    rules:
    - alert: HighGpuPowerUsage
      # TODO, switch to ratio when XPUM starts supporting it
      # TODO, before that, set limit to value suitable for GPUs used in the cluster
      annotations:
        description: "Over 99W ({{ $value }}W) power usage over 20s on '{{ $labels.node }}' node '{{ $labels.pci_bdf }}' GPU"
        summary:  "99+W GPU power usage 20+s"
      expr: |
        xpum_power_watts > 99
      for: 20s
      labels:
        severity: warning
    - alert: HighGpuTemperature
      annotations:
        description: "Over 85C ({{ $value }}C) temperature over 20s on '{{ $labels.node }}' node '{{ $labels.pci_bdf }}' GPU tile"
        summary: "85+C GPU tile temperature 20+s"
      expr: |
        xpum_max_temperature_celsius > 85
      for: 20s
      labels:
        severity: warning
    - alert: HighMemoryUsage
      annotations:
        description: "Over 95% ({{ $value }}%) memory usage over 20s on '{{ $labels.node }}' node '{{ $labels.pci_bdf }}' GPU tile"
        summary: "95+% GPU tile memory usage 20+s"
      expr: |
        xpum_memory_ratio > 0.95
      for: 20s
      labels:
        severity: warning
