apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: intel-gpu-resource-driver-service-account-openshift-privileged-role-binding
  namespace: intel-gpu-resource-driver
subjects:
- kind: ServiceAccount
  name: intel-gpu-resource-driver-service-account
  namespace: intel-gpu-resource-driver
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
  apiGroup: rbac.authorization.k8s.io
