# two claim parameters, two containers with different inline resource-claims
apiVersion: gpu.resource.intel.com/v1alpha2
kind: GpuClaimParameters
metadata:
  name: inline-claim-parameters-multiple1
  namespace: default
spec:
  count: 1
  type: "gpu"
  memory: 128
---
apiVersion: gpu.resource.intel.com/v1alpha2
kind: GpuClaimParameters
metadata:
  name: inline-claim-parameters-multiple2
  namespace: default
spec:
  count: 1
  type: "gpu"
  memory: 128
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: test-inline-claim-template1
  namespace: default
spec:
  metadata:
    labels:
      app: inline-resource
  spec:
    resourceClassName: intel-gpu
    allocationMode: Immediate
    parametersRef:
      apiGroup: gpu.resource.intel.com/v1alpha2
      kind: GpuClaimParameters
      name: inline-claim-parameters-multiple1
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: test-inline-claim-template2
  namespace: default
spec:
  metadata:
    labels:
      app: inline-resource
  spec:
    resourceClassName: intel-gpu
    allocationMode: Immediate
    parametersRef:
      apiGroup: gpu.resource.intel.com/v1alpha2
      kind: GpuClaimParameters
      name: inline-claim-parameters-multiple2
---
apiVersion: v1
kind: Pod
metadata:
  name: pause
  labels:
    name: pause
spec:
  containers:
  - name: pause1
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "set && ls -la /dev/dri/ && sleep 30"]
    resources:
      claims:
      - name: resource1
  - name: cont1
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "set && ls -la /dev/dri/ && sleep 30"]
    resources:
      claims:
      - name: resource2
  resourceClaims:
  - name: resource1
    source:
      resourceClaimTemplateName: test-inline-claim-template1
  - name: resource2
    source:
      resourceClaimTemplateName: test-inline-claim-template2
