apiVersion: gpu.resource.intel.com/v1alpha2
kind: GpuClaimParameters
metadata:
  name: inline-claim1-vf
  namespace: default
spec:
  count: 1
  type: "vf"
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: inline-claim1-vf
  namespace: default
spec:
  metadata:
    labels:
      app: inline-resource
  spec:
    resourceClassName: intel-gpu
    parametersRef:
      apiGroup: gpu.resource.intel.com/v1alpha2
      kind: GpuClaimParameters
      name: inline-claim1-vf
---
apiVersion: gpu.resource.intel.com/v1alpha2
kind: GpuClaimParameters
metadata:
  name: inline-claim2-vf
  namespace: default
spec:
  count: 1
  type: "vf"
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: inline-claim2-vf
  namespace: default
spec:
  metadata:
    labels:
      app: inline-resource
  spec:
    resourceClassName: intel-gpu
    parametersRef:
      apiGroup: gpu.resource.intel.com/v1alpha2
      kind: GpuClaimParameters
      name: inline-claim2-vf
---
apiVersion: v1
kind: Pod
metadata:
  name: test-inline-claim-vf
spec:
  restartPolicy: Never
  containers:
  - name: with-resource
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "ls -la /dev/dri/ && sleep 30"]
    resources:
      claims:
      - name: resource1
      - name: resource2
  - name: without-resource
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "ls -la /dev/ && sleep 30"]
  resourceClaims:
  - name: resource1
    source:
      resourceClaimTemplateName: inline-claim1-vf
  - name: resource2
    source:
      resourceClaimTemplateName: inline-claim2-vf
