apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: delayed-monitor-claim
  namespace: default
spec:
  metadata:
    labels:
      app: delayed-monitor-claim
  spec:
    resourceClassName: intel-gpu-monitor
---
apiVersion: v1
kind: Pod
metadata:
  name: delayed-monitor-pod
spec:
  resourceClaims:
  - name: resource
    source:
      resourceClaimTemplateName: delayed-monitor-claim
  restartPolicy: Never
  containers:
  - name: with-resource
    image: busybox:stable
    command: ["sh", "-c", "ls -la /dev/dri/ && sleep 60"]
    resources:
      claims:
      - name: resource
  - name: without-resource
    image: busybox:stable
    command: ["sh", "-c", "ls -la /dev/ && sleep 60"]
