apiVersion: gpu.resource.intel.com/v1alpha2
kind: GpuClaimParameters
metadata:
  name: delayed-pod-2inline-mix-mem-1
  namespace: default
spec:
  count: 2
  type: "vf"
  memory: 1024
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: delayed-pod-2inline-mix-mem-1
  namespace: default
spec:
  metadata:
    labels:
      app: delayed-pod-2inline-mix-mem
  spec:
    resourceClassName: intel-gpu
    parametersRef:
      apiGroup: gpu.resource.intel.com/v1alpha2
      kind: GpuClaimParameters
      name: delayed-pod-2inline-mix-mem-1
---
apiVersion: gpu.resource.intel.com/v1alpha2
kind: GpuClaimParameters
metadata:
  name: delayed-pod-2inline-mix-mem-2
  namespace: default
spec:
  count: 1
  type: "gpu"
  memory: 4096
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: delayed-pod-2inline-mix-mem-2
  namespace: default
spec:
  metadata:
    labels:
      app: delayed-pod-2inline-mix-mem
  spec:
    resourceClassName: intel-gpu
    parametersRef:
      apiGroup: gpu.resource.intel.com/v1alpha2
      kind: GpuClaimParameters
      name: delayed-pod-2inline-mix-mem-2
---
apiVersion: v1
kind: Pod
metadata:
  name: delayed-pod-2inline-mix-mem
spec:
  restartPolicy: Never
  containers:
  - name: with-resource
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "ls -la /dev/dri/ && sleep 30"]
    resources:
      claims:
      - name: resource1
      - name: resource2
  - name: without-resource
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "ls -la /dev/ && sleep 30"]
  resourceClaims:
  - name: resource1
    source:
      resourceClaimTemplateName: delayed-pod-2inline-mix-mem-1
  - name: resource2
    source:
      resourceClaimTemplateName: delayed-pod-2inline-mix-mem-2

