# one claim parameter with half GPU memory, one Pod with two containers: with and without claim
apiVersion: gpu.resource.intel.com/v1alpha2
kind: GpuClaimParameters
metadata:
  name: inline-claim-parameters2
  namespace: default
spec:
  count: 1
  type: "gpu"
  memory: 512
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: test-inline-claim-template2
  namespace: default
spec:
  metadata:
    labels:
      app: inline-resource
  spec:
    resourceClassName: intel-gpu
    parametersRef:
      apiGroup: gpu.resource.intel.com/v1alpha2
      kind: GpuClaimParameters
      name: inline-claim-parameters2
---
apiVersion: v1
kind: Pod
metadata:
  name: test-inline-claim2
spec:
  restartPolicy: Never
  containers:
  - name: with-resource
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "ls -la /dev/dri/ && sleep 60"]
    resources:
      claims:
      - name: resource
  - name: without-resource
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "ls -la /dev/ && sleep 60"]
  resourceClaims:
  - name: resource
    source:
      resourceClaimTemplateName: test-inline-claim-template2
